### ISSUE TITLE
bug with extra commas

### ISSUE THREAD

**Issue by apmckinlay** [joeshaw/gengen#1]
```
 type getter func(generic.T) generic.U
```

became:

```
 type getter func(string,) string
```

note extra comma

similarly

```
 func Get(key generic.T) generic.U {
```

became:

```
 func Get(key string,) string {
```

**Comment by joeshaw** [comment]
Yeah, I've not been able to figure out why this is happening, since I am just using the same AST libraries that `gofmt` uses.  You can work around this by running the code through `gofmt` after `gengen`.

I'll keep looking into this.

**Comment by apmckinlay** [comment]
No big deal, just thought I'd report it.

Thanks for the interesting tool!
